namespace CratePusher.Graphics
{
    public enum TileType
    {
        YellowCrate         =   6,
        RedCrate            =   7,
        BlueCrate           =   8,
        GreenCrate          =   9,
        GrayCrate           =  10,
        TargetField         =  11,
        YellowTargetField   =  24,
        RedTargetField      =  37,
        BlueTargetField     =  50,
        YellowCrateInTarget =  58,
        RedCrateInTarget    =  59,
        BlueCrateInTarget   =  60,
        GreenCrateInTarget  =  61,
        GrayCrateInTarget   =  62,
        GreenTargetField    =  63,
        PlayerDown          =  65,
        PlayerDownWalk1     =  66,
        PlayerDownWalk2     =  67,
        PlayerUp            =  68,
        PlayerUpWalk1       =  69,
        PlayerUpWalk2       =  70,
        GrayTargetField     =  76,
        GreenFloor          =  88,
        GrayFloor           =  89,
        BrownFloor          =  90,
        PlayerRight         =  91,
        PlayerRightWalk1    =  92,
        PlayerRightWalk2    =  93,
        PlayerLeft          =  94,
        PlayerLeftWalk1     =  95,
        PlayerLeftWalk2     =  96,
        RedWall             =  97,
        GrayWall            =  99,
        BrownWall           = 100
    }
}